apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-config
  namespace: default
data:
  KAFKA_ADDR: "kafka:9092"
  GAMESESSION_MATCH_COMPLETED_KAFKA_TOPIC: "gamesession.match.completed"
  RATING_KAFKA_GROUP_ID: "rating.consumer"
  REDIS_ADDR: "redis:6379"
  ADMIN_ADDR: ":2112"
