apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rating-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: rating-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.default.svc.cluster.local:9092
        topic: gamesession.match.completed
        consumerGroup: rating.consumer
        lagThreshold: "10"
