apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: default
  labels:
    app: rating
spec:
  selector:
    app: rating
  type: ClusterIP
  ports:
  - port: 2112
    name: admin
    targetPort: admin
