apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rating-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: rating
  endpoints:
    - port: admin
      path: /metrics
      interval: 15s
