apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          args:
            - --kafka.server=kafka:9092
            - --group.filter=leaderboard.*
          ports:
            - name: metrics
              containerPort: 9308
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
