apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-service
  namespace: default
  labels:
    app: kafka-exporter
spec:
  selector:
    app: kafka-exporter
  ports:
    - name: metrics
      port: 9308
      targetPort: metrics
