apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          env:
            - name: REDIS_ADDR
              value: redis:6379
          ports:
            - name: metrics
              containerPort: 9121
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
