apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
  namespace: default
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - name: metrics
      port: 9121
      targetPort: metrics
