apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-ingester-config
  namespace: default
data:
  KAFKA_URL: "kafka:9092"
  KAFKA_TOPIC: "leaderboard.match.completed"
  KAFKA_GROUP_ID: "leaderboard.ingester"
  REDIS_ADDR: "redis:6379"
  METRICS_ADDR: ":2112"
