apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: leaderboard-ingester-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: leaderboard-ingester-deployment
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.default.svc.cluster.local:9092
        topic: leaderboard.match.completed
        consumerGroup: leaderboard.ingester
        lagThreshold: "10"
