apiVersion: v1
kind: Service
metadata:
  name: leaderboard-ingester-service
  namespace: default
spec:
  selector:
    app: leaderboard-ingester
  type: ClusterIP
  ports:
  - port: 2112
    name: admin
    targetPort: admin
